cli_tools/common/image/importer/api_inflater.go
cli_tools/common/utils/daisyutils/daisy_utils.go
cli_tools/common/utils/daisyutils/daisy_utils_test.go
cli_tools/gce_ovf_export/exporter/instance_disks_exporter.go
cli_tools/gce_ovf_export/exporter/instance_disks_exporter_test.go
cli_tools/gce_ovf_export/exporter/instance_export_cleaner_test.go
cli_tools/gce_ovf_export/exporter/instance_export_preparer_test.go
cli_tools/gce_ovf_import/daisy_utils/data_disk_workflow_updater.go

In #3, we changed references of `compute-image-tools` to `compute-image-import`; the references for the debian worker images need to come from compute-image-tools.
This is currently causing the OVF export test to fail with `can't use image "projects/compute-image-import/global/images/family/debian-9-worker"`
https://oss-prow.knative.dev/view/gs/compute-image-import-prow/logs/compute-image-import-ovf-export-e2e-tests-daily/1516127665080242176

Revert image references for debian workers

---

daisy_workflows/image_import/windows/translate.ps1

We install `google-compute-engine-metadata-scripts` to simplify scheduling startup tasks on Windows VMs.
This package creates and schedules a task `GCEStartup` that later reads the value of `windows-startup-script-ps1` stored in metadata.
For some reason, on Windows-10 VMs this task assigned a wrong activation value and therefore is not invoked on startup.
After reinstalling the package this issue is solved. See this [PR](https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1165) for details.
However, it corrupts the activation time of `GCEStartup` on Windows-8.1 VMs. Therefore we need to check the Windows version before reinstalling this package.
One small note, we need to compare the version with a string value instead of a number, otherwise this check will fail for numbers …

Fix Windows-8.1 e2e test failures.

---

cli_tools/gce_onestep_image_import/README.md

Changed the github path to compute-image-import at line#14.

CLI Tools: Update ReadMe to fix the github URL

---

cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/aws_test_utils.go
cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go

OneStepImageImport_e2e_use_debian_ami_for_no_default_network_and_remove_windows_ami_test
Update OneStepImageImport e2e tests:
- removed aws-windows-ami & add new aws-debian-ami
- changed the aws images IDs & path of cred file to WAW team aws account resources (in this [PR](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1643))
Why we added a new Linux(Debain) test for "no-default-network" test instead of using ubuntu image?
- because ubuntu-ami is already used in another test, and when tests run in parallel, we cannot have 2 active aws export, we have this error "ResourceCountExceeded: You already reached the maximum limit (1) of active export image tasks status code: 400", So we decided to create a new linux AMI image (Debian) for now just to pass the e2e test and then we will …

OneStepImageImport_e2e_use_debian_ami_for_no_default_network_and_remove_windows_ami_test

---

docs/image-import.md

Please review the workflow files for other operating systems as well. Shouldn't this be the daisy-workflow files in the compute-image-import repo?

doc: add Win 2022 support and update OS details

---

daisy_workflows/image_build/debian/README.md
daisy_workflows/image_build/debian/debian_worker.wf.json
debian_worker_cloudbuild.yaml

Adding an additional variable to the debian_worker.wf.json to associate a new Debian worker image with a specific commit hash (short sha, 6 hex chars). By default, this value will be empty (e.g. if run manually outside CI).
See example below:
/cc @yswe @MahmoudNada0 
/assign @yswe

Add commit hash to description of Debian worker image

---

debian_worker_cloudbuild.yaml

PR addresses incorrect family tag for Debian 10 and 11 workers.
/cc @yswe 
/assign @yswe

Fix family tag for Debian worker images

---

cli_tools/gce_onestep_image_import/onestep_importer/aws_importer_test.go
cli_tools/gce_onestep_image_import/onestep_importer/utils_test.go

We have to call Close in the end of unit tests for writers, so they flush their output to their string variables.

Fix AWS unit tests.

---

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go

As agreed, we will keep supporting RHEL-6 but dropping it's e2e test.
/cc yswe
/assign yswe

ImageImport_drop_rhel_6_e2e_test

---

cli_tools_tests/module/diskinspect/disk_inspect_test.go

Fix opensuse module test by adding reference to family instead of full image uri
/cc yswe
/assign yswe

ImageImport_fix_opensuse_module_test

---

daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
daisy_workflows/image_import/suse/translate_suse.wf.json

Some SLES tests have started failing since the end of July because of timeouts. SLES import uses E2 instances that can be not optimal for the import processes. The idea is to stay consistent with other Linux distributions and to use N1 instances.
On the other side, as N2 instances provide better performance than N1 we can update the import for SLES to start using N2 and check how it goes. It will be a good starting point before updating machine types for other distributions and tools.

Start using N2 instances for SLES import.

---

daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
daisy_workflows/image_import/suse/translate_suse.wf.json

Using N2 instances in import tests leads to E2E tests crashes due to quota limits. As we are going to create a release soon, the migration to N2 will be done in the context of a different task.

Use N1 instances for now due to quotas limitations.

---

daisy_workflows/image_import/enterprise_linux/translate.py
daisy_workflows/image_import/suse/suse_import/translate.py
daisy_workflows/linux_common/utils/common.py

Allow SUSE import to proceed when /etc/resolv.conf is immutable
/cc yswe
/assign yswe

Allow SUSE import to proceed when /etc/resolv.conf is immutable

---

cli_tools/common/image/importer/bootable_disk_processor.go
cli_tools/common/image/importer/bootable_disk_processor_test.go
cli_tools_tests/e2e/gce_ovf_export/test_suites/instance_ovf_export/instance_ovf_export_test_suite.go
cli_tools_tests/e2e/gce_ovf_import/scripts/ovf_import_test_3_disks.sh
cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go
cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
daisy_workflows/image_import/enterprise_linux/translate.py
daisy_workflows/image_import/enterprise_linux/translate_el.wf.json

Import / Export tools are built on the assumption that worker disks of
Linux workers will always receive the name `/dev/sda`. It worked well up
to Debian-10 workers. Since Debian-11 this assumption has stopped
working and the names are assigned quite randomly. It leads to the cases
when the worker disk receives the name `/dev/sdb` that breaks the
behaviour of our tools.
This commit updates RHEL workflows (where we already use Debian-11
workers) in the way that input disks are attached after a worker
instance is created, so the worker disk of this instance will always
receive the name `/dev/sda`.
The solution is temporary, in the future we will implement
auto-detection logic for worker disks.
/cc @MahmoudNada0
/hold

Attach disks to the worker after it is created.

---

daisy_workflows/image_import/inspection/README.md
daisy_workflows/image_import/inspection/boot-inspect.wf.json
daisy_workflows/image_import/inspection/daisy-shim.sh
daisy_workflows/image_import/inspection/src/boot_inspect/cli.py

ImageImport attach disks to inspection worker instance after its created and update inspection worker image.
For more details, read this [description](https://github.com/GoogleCloudPlatform/compute-image-import/pull/56#issue-1351139289).
/assign yswe
/cc yswe

ImageImport_attach_disks_to_inspection_worker_instance_after_its_created

---

cli_tools_tests/module/diskinspect/disk_inspect_test.go

Image Import: Fix inspection module tests.
The inspection module tests depend on Google Cloud official images, when some images are deprecated and removed the tests start failing.
In the context of this PR we are updating the tests to start using families instead of direct links to images for SLES.
In the future we should stop using official images for testing as they make our tests fragile.
/assign @MahmoudNada0 
/hold

Image Import: Fix inspection module tests.

---

daisy_workflows/image_import/suse/suse_import/translate.py

SLES images can refer to outdated packages database and then import will fail during installing the package sle-module-public-cloud in the translation step.
Therefore we will update packages database with Zypper before running the translation.

Fix E2E SLES tests.

---

daisy_workflows/image_import/suse/suse_import/translate.py

This is an update to the previous PR https://github.com/GoogleCloudPlatform/compute-image-import/pull/60. Zypper requires an active subscription to install updates. However, if the image is intended to be used on GCE with a PAYG license, then it doesn't need to have a subscritpion. And therefore we can request Zypper updates only for BYOL images.

Fix SLES PAYG E2E tests.

---

daisy_workflows/image_import/suse/suse_import/translate.py

Some users can rely on specific versions of libraries installed on their images, therefore we shouldn't update packages by default.
Reverting this change temporary before the upcoming release. We will add a flag in the future that will enable this update.

Remove Zypper update from the flow.

---

cli_tools/common/utils/daisyutils/daisy_utils.go

ImageImport remove windows-11 x86 mapping as Microsoft now has ended support for 32-bit operating systems
/cc yswe
/assign yswe

ImageImport_remove_windows_11_x86_mapping

---

daisy_workflows/image_build/debian/debian_worker.sh

Adding support for RHEL-9 OS require upgrading libguestFS version to be v1.46.2 or more. For now we'll use latest version available on debian packages of libguesFS which is v.1.48.2
/assign yswe
/cc yswe

ImageImport_use_latest_libguestfs_version_from_debian

---

cli_tools_tests/module/diskinspect/disk_inspect_test.go
daisy_workflows/image_import/inspection/boot-inspect.wf.json

Use the new worker image with pre installed protobuf in the inspection workflow & Add new module test to assure that inspection step will not fail if -no_external_ip is used without cloud-NAT
/assign yswe
/cc yswe

Use worker image with pre installed protobuf in the inspection workflow

---

daisy_integration_tests/debian_10_worker.wf.json
daisy_integration_tests/debian_11_worker.wf.json
daisy_integration_tests/debian_worker.subwf.json

Currently we don't validate in the integration tests if the changes done to worker images will be compatible with the translation step.
This PR adds validation to the debian worker images by running the translation using the latest version of these worker images (built on the fly).
/cc @MahmoudNada0 @michaljankowiak 
/hold

Integration test for workers and translation.

---

daisy_workflows/image_import/enterprise_linux/translate.py
daisy_workflows/image_import/suse/suse_import/translate.py
daisy_workflows/linux_common/utils/common.py

Make the Import process don't fail if dracut or depmod failes for any reason in SUSE & run depmod command before dracut command.
/cc @yswe

Dont fail if dracut or depmod commands failed for SUSE and Enterprise Linux

---

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go

I created new Enterprise-Linux images (RHEL-9 & Centos-7) and prepared them to replace Centos-8 images that are used in e2e tests. In this PR I updated the tests to used new images instead of Centos-8.
/cc @yswe

ImageImport replace Centos-8 images in e2e tests by other Enterprise-Linux OSes

---

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
daisy_workflows/image_import/debian/translate.py

Allow Debian import (translation step) to proceed without issues when the to-be imported image does not has wget or curl installed.
/cc yswe

allow-debian-import-to-proceed-if-the-image-does-not-has-wget-or-curl-installed

---

daisy_workflows/image_import/suse/suse_import/translate.py

Clarifying in the logs which commands failed as a warning for the user. In both the translation serial port logs and in daisy main logs to be clear for the user. 
/cc yswe

SUSE byol translation don't  fail when SUSEConnect commands failed

---

daisy_workflows/linux_common/bootstrap.sh
daisy_workflows/linux_common/utils/common.py

Use apt-get instead of apt for Debian & Ubuntu translation as it's better to be used in scripts and also it cause this: "WARNING: apt does not have a stable CLI interface yet"
/assign @michaljankowiak

Use apt-get instead of apt for Debian & Ubuntu translation as it's better to be used in scripts

---

cli_tools/common/domain/interfaces.go
cli_tools/common/utils/param/param_utils.go
cli_tools/common/utils/param/populator_test.go
cli_tools/common/utils/storage/scratch_bucket_creator.go
cli_tools/common/utils/storage/scratch_bucket_creator_test.go
cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator.go
cli_tools/gce_ovf_import/ovf_importer/ovf_param_validator_test.go
cli_tools/mocks/mock_scratch_bucket_creator.go

Enable uniform bucket level access by default for all created buckets for 3PI support.

Enable uniform bucket level access by default for all created buckets

---

daisy_workflows/image_import/windows/network.ps1

Removing check for insecure TCP port 80 used for packages.cloud.google.com.

Removing TCP 80 check

---

cli_tools_cloudbuild.yaml

Fix typo project name var in latest cloud-build yaml file

---

cli_tools/common/image/importer/api_inflater.go
daisy_workflows/export/disk_export.wf.json
daisy_workflows/export/disk_export_ext.wf.json
daisy_workflows/export/image_export.wf.json
daisy_workflows/export/image_export_ext.wf.json
daisy_workflows/export_metadata/export_metadata.wf.json
daisy_workflows/image_import/inflate_file.wf.json
daisy_workflows/image_import/suse/translate_opensuse_15.wf.json
daisy_workflows/image_import/suse/translate_suse.wf.json
daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json

Update inflation and image export workflows to use Debian Worker-Images from compute-image-import GCP project

Update inflation and image export workflows to use Debian Worker-Images from compute-image-import GCP project

---

cli_tools/common/disk/inspect_test.go
cli_tools/common/utils/logging/logger.go
cli_tools/common/utils/storage/buffered_writer_test.go
cli_tools/go.mod
cli_tools/go.sum
cli_tools_tests/go.mod
cli_tools_tests/module/import/logs_test.go

- Replace protobuf deprecated URL by the new one
- Temporarily comment the 3 tests that override os.Stdout & cause failure when using -coverprofile flag with go test command

Fix GitHub pre-submit tests failure

---

daisy_workflows/image_import/enterprise_linux/translate_rhel_6_byol.wf.json
daisy_workflows/image_import/enterprise_linux/translate_rhel_6_licensed.wf.json

Reverting worker images for rhel6 image import, as upgraded libguestfs seems incompatible.

Reverting worker images for Rhel6 image import

---

cli_tools_tests/module/diskinspect/disk_inspect_test.go

some images used by this test are obsolete , or deleted causing the test to fail.

Replace obsolete images.

---

debian_worker_cloudbuild.yaml

The relevant image family is deprecated, and we can no longer build new images from it (projects/debian-cloud/global/images/family/debian-10)

Remove build for Debian 10 worker

---

gce_ovf_export.Dockerfile
gce_vm_image_export.Dockerfile

This reverts commit 87b41fa6e27fc251f527e5dc51bc14636b010f38.
This change solved no vulnerabilities, reverting it to reduce risk during upcoming rollout

Revert "Use Debian12 base containers in export flows (#161)"

---

cli_tools/common/domain/interfaces.go
cli_tools/common/utils/param/param_utils.go
cli_tools/common/utils/param/populator_test.go
cli_tools/common/utils/storage/scratch_bucket_creator.go
cli_tools/common/utils/storage/scratch_bucket_creator_test.go
cli_tools/common/utils/storage/storage_client.go
cli_tools/mocks/mock_scratch_bucket_creator.go
cli_tools/mocks/mock_storage_client.go

This might be risky.
In case customers are using the scratch bucket to store their own data and rely on the soft deletion policy.

Revert gcs bucket update

---

daisy_workflows/export/disk_resizing_mon.sh
daisy_workflows/export/export_disk.sh
daisy_workflows/export/export_disk_ext.sh

Prior to this change hard-coded device names were used. This caused issues when working with debian-12-worker image, since the device wasn't given a peristent name.

export: Fetch devices by IDs

---

daisy_workflows/export/disk_resizing_mon.sh
daisy_workflows/export/export_disk.sh
daisy_workflows/export/export_disk_ext.sh

This is meant to make the flow more resiliant to DNS failures.
It's done only in export flows, since import flows are deprecated and M2VM should be used instead.

export: Use the MD server IP directly
