GoogleCloudPlatform/compute-image-import

cli_tools_cloudbuild.yaml, rollout/cli_tools_cloudbuild_build.yaml
The darwin target was used for daisy, which we moved to https://github.com/GoogleCloudPlatform/compute-daisy
=> Darwin is not used for import/export artifacts

cli_tools_tests/e2e/gce_image_import_export/test_suites/onestep_import/onestep_import_test_suite.go
=> OneStepImageImport_fix_e2e_test_not_to_change_test_project_config_object_ptr

daisy_workflows/image_import/windows/translate_bootstrap.ps1
For some older Windows images Add-WindowsDriver can fail with a
misleading error "The parameter is incorrect", however, the DISM version
of Add-Driver works fine.
No tests are added, as there is no a Windows-8.1 image in our test
images repository that can reproduce this error.
=> Fallback to DISM Add-Driver.

daisy_integration_tests/scripts/post_translate_test.sh
Fix post_translate script - service command
/cc yswe
/assign yswe
=> ImageImport_fix_post_translate_script_service_command

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
OVF-Import: change e2e test "instance" of ubuntu-18 with LVM test
/cc yswe
/assign yswe
=> OVF_Import_change_e2e_test_instance_of_ubuntu_18_with_LVM_test

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_machine_image_import/ovf_machine_image_import_test_suite.go
OVF-Import: change e2e test "instance" of ubuntu-18 with LVM test - machine image test
/cc yswe
/assign yswe
=> OVF_Import_change_e2e_test_instance_of_ubuntu_1_18_with_LVM_GMA_test

cli_tools/common/image/importer/bootable_disk_processor.go, cli_tools/common/utils/daisyutils/daisy_utils.go, cli_tools/common/utils/daisyutils/daisy_utils_test.go, cli_tools/gce_ovf_import/ovf_utils/ovf_utils.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_tests/module/diskinspect/disk_inspect_test.go, daisy_workflows/image_import/inspection/tests/test-data/images/docker-image-ubuntu-22.04.yaml, daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-ubuntu-2204-jammy-v20220622.yaml, daisy_workflows/image_import/inspection/tests/test-data/images/gcp-image-ubuntu-pro-2204-jammy-v20220622.yaml, daisy_workflows/image_import/ubuntu/translate_ubuntu_2204.wf.json
Image-import add support for ubuntu 22
/assign yswe
/cc yswe
=> Image import add support for ubuntu 22

daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
=> Add new debian-11 workers for RHEL image import workfows

daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
Revert commit df719d69a1ad18dd9f7ffe0531ccea735b1a2cf2
/assign @MahmoudNada0 
/cc @MahmoudNada0
=> Revert Debian Worker

daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
/cc @yswe @MahmoudNada0 
/assign @yswe
=> Update Debian worker for RHEL 8 imports

cli_tools/common/image/importer/process_planner.go, cli_tools/common/utils/daisyutils/daisy_utils.go, cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, cli_tools_tests/module/diskinspect/disk_inspect_test.go, daisy_workflows/image_import/windows/translate.ps1
Image Import add  support for windows-11
/assign yswe
/cc yswe
=> ImageImport_add_support_for_windows_11

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_integration_tests/daisy_e2e.test.gotmpl
=> Image-Import drop e2e tests that tests importing centos8

daisy_workflows/image_import/inspection/daisy-shim.sh
/assign @MahmoudNada0 
/cc @MahmoudNada0
=> Fix quotes.

daisy_workflows/image_import/inspection/boot-inspect.wf.json
Inspection downgrade worker OS to Debian-10
/assign yswe
/cc yswe
=> Inspection_downgrade_worker_OS_to_Debian_10

daisy_workflows/image_build/debian/debian_worker.sh
=> pre-install protobuf~=3.1 in the worker image

daisy_workflows/image_import/enterprise_linux/translate_rhel_8_byol.wf.json, daisy_workflows/image_import/enterprise_linux/translate_rhel_8_licensed.wf.json
=> Use upgraded worker with libguestFS v1.48 in rhel-8 translation

cli_tools/common/utils/daisyutils/workflow_hook_enable_nested_virtualization.go
=> Fix comment.

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
Since we enabled nested virtualization on worker VMs in tests they have started failing with the `IN_USE_ADDRESSES` quota exceeded error.
The idea is to add an additional zone in E2E tests to split the usage of resources between regions.
=> Fix the IN_USE_ADDRESSES quota error.

cli_tools_tests/e2e/gce_image_import_export/test_suites/scripts/post_translate_test.wf.json
=> Nested virtualization in E2E post translate.

cli_tools/gce_onestep_image_import/onestep_importer/importer.go, cli_tools/gce_onestep_image_import/onestep_importer/importer_test.go, gce_onestep_image_import.Dockerfile
=> Allow importing AWS images without specifying --os

cli_tools/common/domain/interfaces.go, cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/scratch_bucket_creator_test.go
=> Uncomment-scratch-bucket-creator-unit-test

cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_import_e2e_common.go, cli_tools_tests/e2e/gce_ovf_import/test_suites/ovf_instance_import/ovf_instance_import_test_suite.go
=> Fix OVF-Import failing e2e ssd-quota test

gce_onestep_image_import.Dockerfile, gce_ovf_export.Dockerfile, gce_ovf_import.Dockerfile, gce_vm_image_import.Dockerfile
=> upgrage-image-import-export-tools-builder-executor-base-image-to-debian-11

daisy_workflows/image_import/enterprise_linux/translate.py
=> Add --skip-broken flag when needed to EL yum install commands

daisy_workflows/linux_common/utils/common.py
=> Add --tmpdir flag to dracut command for SELinux

daisy_integration_tests/scripts/post_translate_test.sh
=> reorder checks functions of e2e post-translate-script

daisy_workflows/image_import/enterprise_linux/translate.py
This is because if yum install fails with BYOL import, it is likely due to this mage doesn't have an active subscription. So, the user should omit `-byol` flag from import command and try again.
=> Do not add --skip-broken flag to EL yum install if -byol flag is enabled

daisy_workflows/image_import/suse/suse_import/translate.py
=> Fix SUSE translation bug to initramFS - run dracut command - for on-demand imports

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go, daisy_workflows/image_import/suse/suse_import/translate.py
=> Add support for opensuse 15.3 & opensuse 15.4

rollout/cli_tools_cloudbuild_build.yaml, rollout/cli_tools_cloudbuild_build_prepare.yaml, rollout/cli_tools_cloudbuild_deploy.yaml, rollout/cli_tools_cloudbuild_rollback.yaml
=> Update rollout CloudBuild yaml files to push wrappers into two GCP projects

rollout/cli_tools_cloudbuild_deploy.yaml
=> Fix cloud-build deploy yaml file to iterate over the GCP projects correctly

gce_image_import_export_tests.Dockerfile, gce_ovf_export_tests.Dockerfile, gce_ovf_import_tests.Dockerfile
=> Update e2e docker files to pull the base image from compute-image-import-test GCP project

daisy_workflows/image_import/suse/translate_suse.wf.json, daisy_workflows/image_import/ubuntu/translate_ubuntu.wf.json
=> rollback SUSE and Ubuntu translation workflows by downgrading the worker image version

cli_tools/common/image/importer/api_inflater.go, daisy_workflows/export/disk_export.wf.json, daisy_workflows/export/disk_export_ext.wf.json, daisy_workflows/export/image_export.wf.json, daisy_workflows/export/image_export_ext.wf.json, daisy_workflows/export_metadata/export_metadata.wf.json, daisy_workflows/image_import/inflate_file.wf.json
=> rollback the worker image upgrade for the inflater-step and image export workflows

daisy_workflows/image_import/enterprise_linux/translate_centos_stream_8.wf.json, daisy_workflows/image_import/enterprise_linux/translate_centos_stream_9.wf.json
=> Upgrade libguestFS version used for CentOS stream by upgrading worker-image version

daisy_integration_tests/centos_7_translate_with_no_enabled_repos.json, daisy_integration_tests/daisy_e2e.test.gotmpl, daisy_workflows/image_import/enterprise_linux/translate.py
=> Allow importing CentOS with no enabled repos when no-guest-env flag is enabled

daisy_integration_tests/daisy_e2e.test.gotmpl
=> fix-daisy-integration-tests-build-failure

daisy_workflows/image_import/windows/translate_windows_10_x64_byol.wf.json, daisy_workflows/image_import/windows/translate_windows_2012_r2.wf.json, daisy_workflows/image_import/windows/translate_windows_2012_r2_byol.wf.json, daisy_workflows/image_import/windows/translate_windows_2016.wf.json, daisy_workflows/image_import/windows/translate_windows_2016_byol.wf.json, daisy_workflows/image_import/windows/translate_windows_2019.wf.json, daisy_workflows/image_import/windows/translate_windows_2019_byol.wf.json, daisy_workflows/image_import/windows/translate_windows_2022.wf.json, daisy_workflows/image_import/windows/translate_windows_2022_byol.wf.json, daisy_workflows/image_import/windows/translate_windows_8_x64_byol.wf.json
Updating Windows Driver location in image import workflow
=> updating Windows driver location to win6.3-signed-nonvme

cli_tools/common/image/importer/request.go, cli_tools/common/utils/param/param_utils.go, cli_tools/common/utils/storage/storage_client.go, cli_tools/gce_vm_image_import/cli/args.go, cli_tools/gce_vm_image_import/cli/args_test.go, cli_tools/gce_vm_image_import/cli/cli.go
=> Add support for Storage API endpoint override

cli_tools_tests/go.mod, cli_tools_tests/go.sum
=> upgrade protobuf version for cli_tools_test

cli_tools_tests/e2e/gce_image_import_export/test_suites/import/import_tests.go
=> Fix wrong overridden API endpoint e2e

cli_tools/common/domain/interfaces.go, cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/scratch_bucket_creator_test.go, cli_tools/common/utils/storage/storage_client.go, cli_tools/mocks/mock_storage_client.go
update bucket attributes to disable soft delete. it does not work when setting it when creating the bucket.
=> Update bucket attributes in order to disable soft delete

cli_tools/common/domain/interfaces.go, cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/common/utils/storage/scratch_bucket_creator_test.go, cli_tools/common/utils/storage/storage_client.go, cli_tools/mocks/mock_storage_client.go
Reverts GoogleCloudPlatform/compute-image-import#155
some  tests are more flaky than before 
https://testgrid.k8s.io/googleoss-compute-image-import#ci-images-import-export-cli-e2e-tests
=> Revert "Update bucket attributes in order to disable soft delete"

cli_tools/common/domain/interfaces.go, cli_tools/common/utils/param/param_utils.go, cli_tools/common/utils/param/populator_test.go, cli_tools/common/utils/storage/scratch_bucket_creator.go, cli_tools/mocks/mock_scratch_bucket_creator.go
This will clear the soft deletion on GCS buckets created by gcloud.
=> Remove soft deletion when GCS bucket is provided as an arg

image_builder/modules/imagebuild/README.md, image_builder/modules/imagebuild/main.tf, image_builder/modules/imagebuild/outputs.tf, image_builder/modules/imagebuild/variables.tf, image_builder/modules/imagebuild/versions.tf
Adding a TF module for experimental image builder usecases.
=> image builder: Introduce image builder tf module
